stages:
  - build
  - publish
variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
build:
  stage: build
  image: adoptopenjdk:latest
  only:
    - master
  tags:
    - build
  cache:
    key: $CI_PROJECT_NAME
    paths:
      - .gradle/
  artifacts:
    name: "$CI_ENVIRONMENT_NAME"
    paths:
      - build/artifacts
  script:
    - chmod +x gradlew
    - ./gradlew build
publish:
  stage: publish
  image: gradle:latest
  tags:
    - gitlab-org
  only:
    - master
  script:
    - chmod +x gradlew
    - gradle publish