stages:
  - build
variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
build:
  stage: build
  tags:
    - build
  image: adoptopenjdk:latest
  only:
    - master
  cache:
    key: $CI_PROJECT_NAME
    paths:
      - .gradle/
  script:
    - ./gradlew build